name: CommandBlocker
version: '${project.version}'
main: net.jadedmc.commandblocker.CommandBlockerPlugin
api-version: 1.13
authors: [JadedMC]
description: Prevent specific commands from being used
website: http://www.jadedmc.net

folia-supported: true

commands:
  commandblocker:
    description: Main plugin command.
    aliases: [cb]

permissions:
  commandblocker.admin:
    description: Gives the player access to the main plugin command.
    default: op
  commandblocker.*:
    description: Gives the player all plugin permissions.
    default: false
    children:
      commandblocker.admin: true