name: CommandBlocker
version: '${project.version}'
main: net.jadedmc.commandblocker.CommandBlockerPlugin
api-version: 1.13
authors: [JadedMC]
description: Prevent specific commands from being used
website: http://www.jadedmc.net

folia-supported: true

softdepend:
  - BetterReload
  - PlaceholderAPI

commands:
  commandblocker:
    description: Main plugin command.
    aliases: [cb]
    permission: commandblocker.admin

permissions:
  commandblocker.admin:
    description: Gives the player access to the main plugin command.
    default: op
  commandblocker.bypass:
    description: Allows the player to bypass any command filters.
    default: op
  commandblocker.*:
    description: Gives the player all plugin permissions.
    default: false
    children:
      commandblocker.admin: true
      commandblocker.bypass: true